version: '3'
services:
  webapp:
    image: m1chiel/webapp
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
    environment:
      MONGO_URL: "mongodb://database:27017/webapp"
    depends_on:
      - database

  database:
    image: mongo:4.4.18
    volumes:
      - mongodb_data:/data/db

  test:
    build: .
    command: ["yarn", "test"]
    environment:
      API_URL: "http://webapp:3000"
    depends_on:
      - webapp

volumes:
  mongodb_data:
